# Generated by Django 2.1.5 on 2019-02-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0087_auto_20190208_0326'),
        ('product', '0077_auto_20181117_1830'),
    ]

    operations = [
    ]
