# Generated by Django 2.1.5 on 2019-02-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20181117_1830'),
        ('checkout', '0017_auto_20190130_0207'),
    ]

    operations = [
    ]
