# Generated by Django 2.1.5 on 2019-02-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_order_checkout_token'),
        ('order', '0064_auto_20181117_1830'),
    ]

    operations = [
    ]
