# Generated by Django 2.1.5 on 2019-02-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20181117_1830'),
        ('account', '0024_auto_20181011_0737'),
    ]

    operations = [
    ]
